--复仇女神 伊芙
function c99993016.initial_effect(c)
	--Synchro
	aux.AddSynchroProcedure(c,aux.FilterBoolFunction(Card.IsRace,RACE_MACHINE),aux.NonTuner(Card.IsRace,RACE_MACHINE),1)
	c:EnableReviveLimit()
	--
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_QUICK_O)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EVENT_CHAINING)
	e1:SetCountLimit(1)
	e1:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e1:SetRange(LOCATION_MZONE)
		e1:SetCode(EFFECT_IMMUNE_EFFECT)
		e1:SetValue(function(e,te)
			return te:IsHasType(0x7f0) and te:GetOwner()~=e:GetOwner()
		end)
		e1:SetReset(RESET_EVENT+0x1fe0000+RESET_CHAIN)
		e:GetHandler():RegisterEffect(e1)
	end)
	c:RegisterEffect(e1)
	--
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e2:SetCode(EVENT_BATTLE_DAMAGE)
	e2:SetProperty(EFFECT_FLAG_DAMAGE_STEP)
	e2:SetRange(LOCATION_MZONE)
	e2:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)
		return ep~=tp
	end)
	e2:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local val=1
		if Duel.GetTurnPlayer()~=tp then val=2 end
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_FIELD)
		e1:SetCode(EFFECT_CANNOT_TO_HAND)
		e1:SetTargetRange(LOCATION_DECK,LOCATION_DECK)
		e1:SetCondition(function(e,re,rp)
			return Duel.GetCurrentPhase()~=PHASE_DRAW
				and rp~=e:GetHandlerPlayer()
		end)
		e1:SetReset(RESET_PHASE+PHASE_END+RESET_OPPO_TURN,val)
		Duel.RegisterEffect(e1,tp)
		local e2=e1:Clone()
		e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e2:SetCode(EFFECT_CANNOT_DRAW)
		e2:SetTargetRange(0,1)
		Duel.RegisterEffect(e2,tp)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetCode(EFFECT_UPDATE_ATTACK)
		e3:SetValue(700)
		e3:SetReset(RESET_EVENT+0x1fe0000)
		c:RegisterEffect(e3)
	end)
	c:RegisterEffect(e2)
end
c99993016.Remi_named_with_eve=true